### ISSUE TITLE
Accounts Show As Inactive After Refresh

### ISSUE THREAD

**Issue by Deafwave** [GregLando113/gwlauncher#1]
If I launch a couple of clients, and they show up as "Active", right clicking -> refresh or launching another client causing it to refresh automatically will trigger all of the accounts to get set back to "Inactive".

R4 only, R3 didn't have this problem. Though, when I go back and use R3 now, it has this problem? I couldn't find any settings in %appdata% or %localappdata% so I'm unsure if it's my computer, or what is going on.

Thanks!

**Comment by GregLando113** [comment]
Heya,

Yeah this is due to the update to GW 1-2 weeks ago, I havent gotten around to updating it, but hopefully r5 will come out sometime within the next couple of days fixing this, thank you for your notifications.

And just to clarify, theres no settings or files saved anywhere other than the GW Launcher folder :)
