### ISSUE TITLE
Running Release 11, exe does not bring up json file, located task in Task Manager

### ISSUE THREAD

**Issue by kenwms** [GregLando113/gwlauncher#16]
I'm running windows 10, 64 bit. I also run McAfee security.
Any ideas to try to get it to work?

Thanks,

**Comment by Explomatic** [comment]
What exactly is the issue? I'm running r11 as well and was confused for a while that the regular UI was not showing up, but the process was visible in the Task Manager. Turns out, it's now placed in the right side of the taskbar:
![image](https://user-images.githubusercontent.com/14542568/89123425-8bfaa700-d4cf-11ea-839d-d4fb28d814b0.png)

**Comment by DubbleClick** [comment]
r12 is out now
