### ISSUE TITLE
Latest Version Crashing

### ISSUE THREAD

**Issue by cceller** [GregLando113/gwlauncher#9]
Thank you for this wonderful work. I am using your latest update after the December game update. I get to the screen when I am about to enter a town (example Kamadan screen as I am about to enter for the first time after login) and game crashes. 

I can provide that log if needed. Windows 10, 64bit.

Thanks.

**Comment by GregLando113** [comment]
Are you using any plugins? check your gw.exe folder and the launcher folder for plugins. Otherwise make sure your datfile is -imaged. If you are using the datfix and you are not -imaged you can crash for a nonexistant asset.

**Comment by cceller** [comment]
Hi Greg,

Thanks for taking time to reply during the holidays. I did delete my .dat file and start over, same result. I am including the crash file, attached as a Word doc.

Game runs normally using the standard client, outside of the launcher. Had no issues with the version prior to the update also.

Cheers,

Chad



________________________________

**Comment by cceller** [comment]
Hi Greg,

I did a total uninstall / reg clean / reinstall, this time on my C drive instead of D. Downloaded all files via -image.

Same scenario.

File attached.

Thanks and again happy holidays!

________________________________

**Comment by cceller** [comment]
If I do not choose the dat patch option the launcher opens the game normally (of course I can't launch a second client without the dat patch option). I have used -image multiple times so I am not sure what else I can try. I have chatted with a couple of people with no problems so this must be me.

**Comment by bshin19** [comment]
Until this is fixed, just copy your guildwars folder from program files x86 and point your accounts to different instances of guild wars without the dat patch applied.

**Comment by BearsMan** [comment]
ok so inside the GW Client shortcut file if u right click and go to properties under target will look like this: "C:\Program Files (x86)\Guild Wars\Guild Wars\Gw.exe" make sure after the last quote press space bar once then add -image after that hit apply/ok then launch the game by itself but don't do anything because what that will do is force the game to download the latest update that was applied, after it's finished go back to properties (right-click guild wars desktop icon) then go to properties again just remove -image from the target line then launch the game as normal then it should work

**Comment by cceller** [comment]
.dat patch checkbox gets me everytime.

For now I am just using the launcher to point to installs on the C and D drive. Less elegant but it works and the .dat patch feature isnt needed.
________________________________
